from controller.autotrack.LightController import LightController
from model.virtual_filters import AutoTrackerFilter

class VFilterLightController(LightController):
    """
    This class acts as a gateway between the remote detection thread and
    the change propagation of the constants generated by the v-filter.
    """

    def __init__(self, f: AutoTrackerFilter):
        pass

    # TODO implement as in ArtNet.py from BA
