"""Module containing and exporting all available filter nodes"""
from model.filter import FilterTypeEnumeration
from view.show_mode.editor.nodes.impl.adapters import (
                                                       Adapter8bitToFloat,
                                                       Adapter8BitToRangeFloat,
                                                       Adapter16BitTo8BitNode,
                                                       Adapter16BitToBoolNode,
                                                       Adapter16bitToFloat,
                                                       Adapter16BitToRangeFloat,
                                                       AdapterColorToFloatsNode,
                                                       AdapterColorToRGBNode,
                                                       AdapterColorToRGBWANode,
                                                       AdapterColorToRGBWNode,
                                                       AdapterFloatTo8BitRange,
                                                       AdapterFloatTo16BitRange,
                                                       AdapterFloatToColorNode,
                                                       AdapterFloatToRange,
                                                       ColorBrightnessMixinNode,
                                                       CombineTwo8BitToSingle16Bit,
                                                       Map8BitTo16Bit,
)
from view.show_mode.editor.nodes.impl.arithmetics import (
                                                       ArithmeticExponentialNode,
                                                       ArithmeticFloatTo8BitNode,
                                                       ArithmeticFloatTo16BitNode,
                                                       ArithmeticLogarithmNode,
                                                       ArithmeticMACNode,
                                                       ArithmeticMaximumNode,
                                                       ArithmeticMinimumNode,
                                                       ArithmeticRoundNode,
                                                       Sum8BitNode,
                                                       Sum16BitNode,
                                                       SumFloatNode,
)
from view.show_mode.editor.nodes.impl.color_manip_nodes import (
                                                       ColorMixerAdditiveRGBNode,
                                                       ColorMixerHSVNode,
                                                       ColorMixerNormativeRGBNode,
                                                       ColorMixerVFilterNode,
)
from view.show_mode.editor.nodes.impl.constants import (
                                                       Constants8BitNode,
                                                       Constants16BitNode,
                                                       ConstantsColorNode,
                                                       ConstantsFloatNode,
                                                       PanTiltConstant,
)
from view.show_mode.editor.nodes.impl.debug import (
                                                       Debug8BitNode,
                                                       Debug16BitNode,
                                                       DebugColorNode,
                                                       DebugFloatNode,
                                                       DebugRemote8BitNode,
                                                       DebugRemote16BitNode,
                                                       DebugRemoteColorNode,
                                                       DebugRemoteFloatNode,
)
from view.show_mode.editor.nodes.impl.effects import (
                                                       AutoTrackerNode,
                                                       CueListNode,
                                                       EffectsStackNode,
                                                       Shift8BitNode,
                                                       Shift16BitNode,
                                                       ShiftColorNode,
                                                       ShiftFloatNode,
)
from view.show_mode.editor.nodes.impl.faders import (
                                                       FaderHSIANode,
                                                       FaderHSIAUNode,
                                                       FaderHSINode,
                                                       FaderHSIUNode,
                                                       FaderMainBrightness,
                                                       FaderRawNode,
)
from view.show_mode.editor.nodes.impl.scripting import LuaFilterNode
from view.show_mode.editor.nodes.impl.time import (
                                                       TimeNode,
                                                       TimeSwitchOffDelay8BitNode,
                                                       TimeSwitchOffDelay16BitNode,
                                                       TimeSwitchOffDelayFloatNode,
                                                       TimeSwitchOnDelay8BitNode,
                                                       TimeSwitchOnDelay16BitNode,
                                                       TimeSwitchOnDelayFloatNode,
)
from view.show_mode.editor.nodes.impl.trigonometics import (
                                                       TrigonometricArcCosNode,
                                                       TrigonometricArcSinNode,
                                                       TrigonometricArcTanNode,
                                                       TrigonometricCosineNode,
                                                       TrigonometricSineNode,
                                                       TrigonometricTangentNode,
)
from view.show_mode.editor.nodes.impl.universenode import UniverseNode
from view.show_mode.editor.nodes.impl.waves import SawtoothWaveNode, SquareWaveNode, TriangleWaveNode
from view.show_mode.editor.nodes.import_node import ImportNode

type_to_node: dict[int, str] = {
    FilterTypeEnumeration.VFILTER_COLOR_MIXER: ColorMixerVFilterNode.node_name,
    FilterTypeEnumeration.VFILTER_IMPORT: ImportNode.node_name,
    FilterTypeEnumeration.VFILTER_COLOR_GLOBAL_BRIGHTNESS_MIXIN: ColorBrightnessMixinNode.node_name,
    FilterTypeEnumeration.VFILTER_POSITION_CONSTANT: PanTiltConstant.node_name,
    FilterTypeEnumeration.VFILTER_CUES: CueListNode.node_name,
    FilterTypeEnumeration.VFILTER_AUTOTRACKER: AutoTrackerNode.node_name,
    FilterTypeEnumeration.VFILTER_EFFECTSSTACK: EffectsStackNode.node_name,
    FilterTypeEnumeration.FILTER_CONSTANT_8BIT: Constants8BitNode.node_name,
    FilterTypeEnumeration.FILTER_CONSTANT_16_BIT: Constants16BitNode.node_name,
    FilterTypeEnumeration.FILTER_CONSTANT_FLOAT: ConstantsFloatNode.node_name,
    FilterTypeEnumeration.FILTER_CONSTANT_COLOR: ConstantsColorNode.node_name,
    FilterTypeEnumeration.FILTER_DEBUG_OUTPUT_8BIT: Debug8BitNode.node_name,
    FilterTypeEnumeration.FILTER_DEBUG_OUTPUT_16BIT: Debug16BitNode.node_name,
    FilterTypeEnumeration.FILTER_DEBUG_OUTPUT_FLOAT: DebugFloatNode.node_name,
    FilterTypeEnumeration.FILTER_DEBUG_OUTPUT_COLOR: DebugColorNode.node_name,
    FilterTypeEnumeration.FILTER_ADAPTER_16BIT_TO_DUAL_8BIT: Adapter16BitTo8BitNode.node_name,
    FilterTypeEnumeration.FILTER_ADAPTER_16BIT_TO_BOOL: Adapter16BitToBoolNode.node_name,
    FilterTypeEnumeration.FILTER_ARITHMETICS_MAC: ArithmeticMACNode.node_name,
    FilterTypeEnumeration.FILTER_UNIVERSE_OUTPUT: UniverseNode.node_name,
    FilterTypeEnumeration.FILTER_ARITHMETICS_FLOAT_TO_16BIT: ArithmeticFloatTo16BitNode.node_name,
    FilterTypeEnumeration.FILTER_ARITHMETICS_FLOAT_TO_8BIT: ArithmeticFloatTo8BitNode.node_name,
    FilterTypeEnumeration.FILTER_ARITHMETICS_ROUND: ArithmeticRoundNode.node_name,
    FilterTypeEnumeration.FILTER_ADAPTER_COLOR_TO_RGB: AdapterColorToRGBNode.node_name,
    FilterTypeEnumeration.FILTER_ADAPTER_COLOR_TO_RGBW: AdapterColorToRGBWNode.node_name,
    FilterTypeEnumeration.FILTER_ADAPTER_COLOR_TO_RGBWA: AdapterColorToRGBWANode.node_name,
    FilterTypeEnumeration.FILTER_ADAPTER_FLOAT_TO_COLOR: AdapterFloatToColorNode.node_name,
    FilterTypeEnumeration.FILTER_TRIGONOMETRICS_SIN: TrigonometricSineNode.node_name,
    FilterTypeEnumeration.FILTER_TRIGONOMETRICS_COSIN: TrigonometricCosineNode.node_name,
    FilterTypeEnumeration.FILTER_TRIGONOMETRICS_TANGENT: TrigonometricTangentNode.node_name,
    FilterTypeEnumeration.FILTER_TRIGONOMETRICS_ARCSIN: TrigonometricArcSinNode.node_name,
    FilterTypeEnumeration.FILTER_TRIGONOMETRICS_ARCCOSIN: TrigonometricArcCosNode.node_name,
    FilterTypeEnumeration.FILTER_TRIGONOMETRICS_ARCTANGENT: TrigonometricArcTanNode.node_name,
    FilterTypeEnumeration.FILTER_WAVES_SQUARE: SquareWaveNode.node_name,
    FilterTypeEnumeration.FILTER_WAVES_TRIANGLE: TriangleWaveNode.node_name,
    FilterTypeEnumeration.FILTER_WAVES_SAWTOOTH: SawtoothWaveNode.node_name,
    FilterTypeEnumeration.FILTER_ARITHMETICS_LOGARITHM: ArithmeticLogarithmNode.node_name,
    FilterTypeEnumeration.FILTER_ARITHMETICS_EXPONENTIAL: ArithmeticExponentialNode.node_name,
    FilterTypeEnumeration.FILTER_ARITHMETICS_MINIMUM: ArithmeticMinimumNode.node_name,
    FilterTypeEnumeration.FILTER_ARITHMETICS_MAXIMUM: ArithmeticMaximumNode.node_name,
    FilterTypeEnumeration.FILTER_TYPE_TIME_INPUT: TimeNode.node_name,
    FilterTypeEnumeration.FILTER_TIME_SWITCH_ON_DELAY_8BIT: TimeSwitchOnDelay8BitNode.node_name,
    FilterTypeEnumeration.FILTER_TIME_SWITCH_ON_DELAY_16BIT: TimeSwitchOnDelay16BitNode.node_name,
    FilterTypeEnumeration.FILTER_TIME_SWITCH_ON_DELAY_FLOAT: TimeSwitchOnDelayFloatNode.node_name,
    FilterTypeEnumeration.FILTER_TIME_SWITCH_OFF_DELAY_8BIT: TimeSwitchOffDelay8BitNode.node_name,
    FilterTypeEnumeration.FILTER_TIME_SWITCH_OFF_DELAY_16BIT: TimeSwitchOffDelay16BitNode.node_name,
    FilterTypeEnumeration.FILTER_TIME_SWITCH_OFF_DELAY_FLOAT: TimeSwitchOffDelayFloatNode.node_name,
    FilterTypeEnumeration.FILTER_FADER_RAW: FaderRawNode.node_name,
    FilterTypeEnumeration.FILTER_FADER_HSI: FaderHSINode.node_name,
    FilterTypeEnumeration.FILTER_FADER_HSIA: FaderHSIANode.node_name,
    FilterTypeEnumeration.FILTER_FADER_HSIU: FaderHSIUNode.node_name,
    FilterTypeEnumeration.FILTER_FADER_HSIAU: FaderHSIAUNode.node_name,
    FilterTypeEnumeration.FILTER_TYPE_CUES: CueListNode.node_name,
    FilterTypeEnumeration.FILTER_EFFECT_SHIFT_8BIT: Shift8BitNode.node_name,
    FilterTypeEnumeration.FILTER_EFFECT_SHIFT_16BIT: Shift16BitNode.node_name,
    FilterTypeEnumeration.FILTER_EFFECT_SHIFT_FLOAT: ShiftFloatNode.node_name,
    FilterTypeEnumeration.FILTER_EFFECT_SHIFT_COLOR: ShiftColorNode.node_name,
    FilterTypeEnumeration.FILTER_TYPE_MAIN_BRIGHTNESS: FaderMainBrightness.node_name,
    FilterTypeEnumeration.FILTER_SCRIPTING_LUA: LuaFilterNode.node_name,
    FilterTypeEnumeration.FILTER_TYPE_ADAPTER_8BIT_TO_FLOAT: Adapter8bitToFloat.node_name,
    FilterTypeEnumeration.FILTER_TYPE_ADAPTER_16BIT_TO_FLOAT: Adapter16bitToFloat.node_name,
    FilterTypeEnumeration.FILTER_ADAPTER_COLOR_TO_FLOAT: AdapterColorToFloatsNode.node_name,
    FilterTypeEnumeration.FILTER_ADAPTER_FLOAT_TO_8BIT_RANGE: AdapterFloatTo8BitRange.node_name,
    FilterTypeEnumeration.FILTER_ADAPTER_FLOAT_TO_16BIT_RANGE: AdapterFloatTo16BitRange.node_name,
    FilterTypeEnumeration.FILTER_ADAPTER_FLOAT_TO_FLOAT_RANGE: AdapterFloatToRange.node_name,
    FilterTypeEnumeration.FILTER_ADAPTER_DUAL_BYTE_TO_16BIT: CombineTwo8BitToSingle16Bit.node_name,
    FilterTypeEnumeration.FILTER_ADAPTER_8BIT_TO_16BIT: Map8BitTo16Bit.node_name,
    FilterTypeEnumeration.VFILTER_FILTER_ADAPTER_16BIT_TO_FLOAT_RANGE: Adapter16BitToRangeFloat.node_name,
    FilterTypeEnumeration.VFILTER_FILTER_ADAPTER_8BIT_TO_FLOAT_RANGE: Adapter8BitToRangeFloat.node_name,
    FilterTypeEnumeration.FILTER_COLOR_MIXER_HSV: ColorMixerHSVNode.node_name,
    FilterTypeEnumeration.FILTER_COLOR_MIXER_ADDITIVE_RGB: ColorMixerAdditiveRGBNode.node_name,
    FilterTypeEnumeration.FILTER_COLOR_MIXER_NORMATVE_RGB: ColorMixerNormativeRGBNode.node_name,
    FilterTypeEnumeration.FILTER_SUM_8BIT: Sum8BitNode.node_name,
    FilterTypeEnumeration.FILTER_SUM_16BIT: Sum16BitNode.node_name,
    FilterTypeEnumeration.FILTER_SUM_FLOAT: SumFloatNode.node_name,
    FilterTypeEnumeration.FILTER_REMOTE_DEBUG_8BIT: DebugRemote8BitNode.node_name,
    FilterTypeEnumeration.FILTER_REMOTE_DEBUG_16BIT: DebugRemote16BitNode.node_name,
    FilterTypeEnumeration.FILTER_REMOTE_DEBUG_FLOAT: DebugRemoteFloatNode.node_name,
    FilterTypeEnumeration.FILTER_REMOTE_DEBUG_PIXEL: DebugRemoteColorNode.node_name,
}
