"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class dmx_output(google.protobuf.message.Message):
    """
    This file specifies messages and types used in direct mode.

    Set the content of a universe or receive requested information about a universe
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    UNIVERSE_ID_FIELD_NUMBER: builtins.int
    CHANNEL_DATA_FIELD_NUMBER: builtins.int
    universe_id: builtins.int
    @property
    def channel_data(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    def __init__(
        self,
        *,
        universe_id: builtins.int = ...,
        channel_data: collections.abc.Iterable[builtins.int] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["channel_data", b"channel_data", "universe_id", b"universe_id"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___dmx_output: typing_extensions.TypeAlias = dmx_output

@typing.final
class request_dmx_data(google.protobuf.message.Message):
    """Request the current universe data"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    UNIVERSE_ID_FIELD_NUMBER: builtins.int
    universe_id: builtins.int
    def __init__(
        self,
        *,
        universe_id: builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["universe_id", b"universe_id"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___request_dmx_data: typing_extensions.TypeAlias = request_dmx_data
