"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class dmx_output(google.protobuf.message.Message):
    """
    This file specifies messages and types used in direct mode.

    Set the content of a universe or receive requested information about a universe
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    UNIVERSE_ID_FIELD_NUMBER: builtins.int
    CHANNEL_DATA_FIELD_NUMBER: builtins.int
    universe_id: builtins.int
    @property
    def channel_data(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    def __init__(
        self,
        *,
        universe_id: builtins.int = ...,
        channel_data: collections.abc.Iterable[builtins.int] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["channel_data", b"channel_data", "universe_id", b"universe_id"]) -> None: ...

global___dmx_output = dmx_output

@typing_extensions.final
class request_dmx_data(google.protobuf.message.Message):
    """Request the current universe data"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    UNIVERSE_ID_FIELD_NUMBER: builtins.int
    universe_id: builtins.int
    def __init__(
        self,
        *,
        universe_id: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["universe_id", b"universe_id"]) -> None: ...

global___request_dmx_data = request_dmx_data
