"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _event_type:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _event_typeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_event_type.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    SINGLE_TRIGGER: _event_type.ValueType  # 0
    START: _event_type.ValueType  # 1
    RELEASE: _event_type.ValueType  # 2
    ONGOING_EVENT: _event_type.ValueType  # 3
    INVALID: _event_type.ValueType  # 255

class event_type(_event_type, metaclass=_event_typeEnumTypeWrapper): ...

SINGLE_TRIGGER: event_type.ValueType  # 0
START: event_type.ValueType  # 1
RELEASE: event_type.ValueType  # 2
ONGOING_EVENT: event_type.ValueType  # 3
INVALID: event_type.ValueType  # 255
Global___event_type: typing_extensions.TypeAlias = event_type

@typing.final
class event(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TYPE_FIELD_NUMBER: builtins.int
    SENDER_ID_FIELD_NUMBER: builtins.int
    SENDER_FUNCTION_FIELD_NUMBER: builtins.int
    EVENT_ID_FIELD_NUMBER: builtins.int
    ARGUMENTS_FIELD_NUMBER: builtins.int
    type: Global___event_type.ValueType
    sender_id: builtins.int
    sender_function: builtins.int
    event_id: builtins.int
    @property
    def arguments(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    def __init__(
        self,
        *,
        type: Global___event_type.ValueType = ...,
        sender_id: builtins.int = ...,
        sender_function: builtins.int = ...,
        event_id: builtins.int = ...,
        arguments: collections.abc.Iterable[builtins.int] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["arguments", b"arguments", "event_id", b"event_id", "sender_function", b"sender_function", "sender_id", b"sender_id", "type", b"type"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___event: typing_extensions.TypeAlias = event

@typing.final
class event_sender(google.protobuf.message.Message):
    """
    GUI -> Fish:
     - If the sender_id does not yet exist, a new event_sender will be instantiated. Otherwise it will be updated.
     - Type is used to instantiate the correct event_sender type. On updates it will be ignored.
     - Name is used to name the new event_sender. On updates it will be ignored.
     - gui_debug_enabled sets or disabled the sending of incomming events to the GUI.
     - configuration is used to update the settings of the event_sender.

    Fish -> GUI:
     - All fields will be populated with the current configuration
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class ConfigurationEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["key", b"key", "value", b"value"]
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    SENDER_ID_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    GUI_DEBUG_ENABLED_FIELD_NUMBER: builtins.int
    CONFIGURATION_FIELD_NUMBER: builtins.int
    sender_id: builtins.int
    type: builtins.str
    name: builtins.str
    gui_debug_enabled: builtins.bool
    @property
    def configuration(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]: ...
    def __init__(
        self,
        *,
        sender_id: builtins.int = ...,
        type: builtins.str = ...,
        name: builtins.str = ...,
        gui_debug_enabled: builtins.bool = ...,
        configuration: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["configuration", b"configuration", "gui_debug_enabled", b"gui_debug_enabled", "name", b"name", "sender_id", b"sender_id", "type", b"type"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___event_sender: typing_extensions.TypeAlias = event_sender
