# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Events.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x45vents.proto\x12\x1bmissiondmx.fish.ipcmessages\"\x8f\x01\n\x05\x65vent\x12\x35\n\x04type\x18\x01 \x01(\x0e\x32\'.missiondmx.fish.ipcmessages.event_type\x12\x11\n\tsender_id\x18\x02 \x01(\r\x12\x17\n\x0fsender_function\x18\x03 \x01(\r\x12\x10\n\x08\x65vent_id\x18\x04 \x01(\x04\x12\x11\n\targuments\x18\x05 \x03(\r\"\xe3\x01\n\x0c\x65vent_sender\x12\x11\n\tsender_id\x18\x01 \x01(\r\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x19\n\x11gui_debug_enabled\x18\x04 \x01(\x08\x12S\n\rconfiguration\x18\x05 \x03(\x0b\x32<.missiondmx.fish.ipcmessages.event_sender.ConfigurationEntry\x1a\x34\n\x12\x43onfigurationEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01*Y\n\nevent_type\x12\x12\n\x0eSINGLE_TRIGGER\x10\x00\x12\t\n\x05START\x10\x01\x12\x0b\n\x07RELEASE\x10\x02\x12\x11\n\rONGOING_EVENT\x10\x03\x12\x0c\n\x07INVALID\x10\xff\x01\x42\x02H\x03\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Events_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\003'
  _EVENT_SENDER_CONFIGURATIONENTRY._options = None
  _EVENT_SENDER_CONFIGURATIONENTRY._serialized_options = b'8\001'
  _EVENT_TYPE._serialized_start=421
  _EVENT_TYPE._serialized_end=510
  _EVENT._serialized_start=46
  _EVENT._serialized_end=189
  _EVENT_SENDER._serialized_start=192
  _EVENT_SENDER._serialized_end=419
  _EVENT_SENDER_CONFIGURATIONENTRY._serialized_start=367
  _EVENT_SENDER_CONFIGURATIONENTRY._serialized_end=419
# @@protoc_insertion_point(module_scope)
