# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FilterMode.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x46ilterMode.proto\x12\x1bmissiondmx.fish.ipcmessages\"\x1f\n\x0b\x65nter_scene\x12\x10\n\x08scene_id\x18\x01 \x01(\x05\"?\n\x0eload_show_file\x12\x11\n\tshow_data\x18\x01 \x01(\t\x12\x1a\n\x12goto_default_scene\x18\x02 \x01(\x08\"g\n\x10update_parameter\x12\x11\n\tfilter_id\x18\x01 \x01(\t\x12\x15\n\rparameter_key\x18\x02 \x01(\t\x12\x17\n\x0fparameter_value\x18\x03 \x01(\t\x12\x10\n\x08scene_id\x18\x04 \x01(\x05*\xa0\x01\n\x12ShowFileApplyState\x12\x10\n\x0cSFAS_INVALID\x10\x00\x12\x14\n\x10SFAS_SHOW_ACTIVE\x10\x01\x12\x15\n\x11SFAS_SHOW_LOADING\x10\x02\x12\x16\n\x12SFAS_SHOW_UPDATING\x10\x03\x12\x16\n\x12SFAS_NO_SHOW_ERROR\x10\x04\x12\x1b\n\x17SFAS_ERROR_SHOW_RUNNING\x10\x05\x42\x02H\x03\x62\x06proto3')

_SHOWFILEAPPLYSTATE = DESCRIPTOR.enum_types_by_name['ShowFileApplyState']
ShowFileApplyState = enum_type_wrapper.EnumTypeWrapper(_SHOWFILEAPPLYSTATE)
SFAS_INVALID = 0
SFAS_SHOW_ACTIVE = 1
SFAS_SHOW_LOADING = 2
SFAS_SHOW_UPDATING = 3
SFAS_NO_SHOW_ERROR = 4
SFAS_ERROR_SHOW_RUNNING = 5


_ENTER_SCENE = DESCRIPTOR.message_types_by_name['enter_scene']
_LOAD_SHOW_FILE = DESCRIPTOR.message_types_by_name['load_show_file']
_UPDATE_PARAMETER = DESCRIPTOR.message_types_by_name['update_parameter']
enter_scene = _reflection.GeneratedProtocolMessageType('enter_scene', (_message.Message,), {
  'DESCRIPTOR' : _ENTER_SCENE,
  '__module__' : 'FilterMode_pb2'
  # @@protoc_insertion_point(class_scope:missiondmx.fish.ipcmessages.enter_scene)
  })
_sym_db.RegisterMessage(enter_scene)

load_show_file = _reflection.GeneratedProtocolMessageType('load_show_file', (_message.Message,), {
  'DESCRIPTOR' : _LOAD_SHOW_FILE,
  '__module__' : 'FilterMode_pb2'
  # @@protoc_insertion_point(class_scope:missiondmx.fish.ipcmessages.load_show_file)
  })
_sym_db.RegisterMessage(load_show_file)

update_parameter = _reflection.GeneratedProtocolMessageType('update_parameter', (_message.Message,), {
  'DESCRIPTOR' : _UPDATE_PARAMETER,
  '__module__' : 'FilterMode_pb2'
  # @@protoc_insertion_point(class_scope:missiondmx.fish.ipcmessages.update_parameter)
  })
_sym_db.RegisterMessage(update_parameter)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\003'
  _SHOWFILEAPPLYSTATE._serialized_start=253
  _SHOWFILEAPPLYSTATE._serialized_end=413
  _ENTER_SCENE._serialized_start=49
  _ENTER_SCENE._serialized_end=80
  _LOAD_SHOW_FILE._serialized_start=82
  _LOAD_SHOW_FILE._serialized_end=145
  _UPDATE_PARAMETER._serialized_start=147
  _UPDATE_PARAMETER._serialized_end=250
# @@protoc_insertion_point(module_scope)
