# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MessageTypes.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12MessageTypes.proto\x12\x1bmissiondmx.fish.ipcmessages*\x88\x04\n\x07MsgType\x12\x10\n\x0cMSGT_NOTHING\x10\x00\x12\x15\n\x11MSGT_UPDATE_STATE\x10\x01\x12\x1d\n\x19MSGT_CURRENT_STATE_UPDATE\x10\x02\x12\x11\n\rMSGT_UNIVERSE\x10\x03\x12\x16\n\x12MSGT_UNIVERSE_LIST\x10\x04\x12\x1e\n\x1aMSGT_REQUEST_UNIVERSE_LIST\x10\x05\x12\x18\n\x14MSGT_DELETE_UNIVERSE\x10\x06\x12\x1c\n\x18MSGT_BUTTON_STATE_CHANGE\x10\x07\x12\x17\n\x13MSGT_FADER_POSITION\x10\x08\x12\x1e\n\x1aMSGT_ROTARY_ENCODER_CHANGE\x10\t\x12\x13\n\x0fMSGT_DMX_OUTPUT\x10\n\x12\x19\n\x15MSGT_REQUEST_DMX_DATA\x10\x0b\x12\x14\n\x10MSGT_ENTER_SCENE\x10\x0c\x12\x17\n\x13MSGT_LOAD_SHOW_FILE\x10\r\x12\x19\n\x15MSGT_UPDATE_PARAMETER\x10\x0e\x12\x14\n\x10MSGT_LOG_MESSAGE\x10\x0f\x12\x1e\n\x1aMSGT_REMOVE_FADER_BANK_SET\x10\x10\x12\x1b\n\x17MSGT_ADD_FADER_BANK_SET\x10\x11\x12\x14\n\x10MSGT_DESK_UPDATE\x10\x12\x12\x16\n\x12MSGT_UPDATE_COLUMN\x10\x13\x42\x02H\x03\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MessageTypes_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\003'
  _MSGTYPE._serialized_start=52
  _MSGTYPE._serialized_end=572
# @@protoc_insertion_point(module_scope)
