"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import FilterMode_pb2
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions
from Console_pb2 import (
    BS_ACTIVE as BS_ACTIVE,
    BS_BUTTON_PRESSED as BS_BUTTON_PRESSED,
    BS_BUTTON_RELEASED as BS_BUTTON_RELEASED,
    BS_SET_LED_BLINKING as BS_SET_LED_BLINKING,
    BS_SET_LED_NOT_ACTIVE as BS_SET_LED_NOT_ACTIVE,
    BTN_ALT as BTN_ALT,
    BTN_AUDIOINST as BTN_AUDIOINST,
    BTN_AUDIOTRACKS as BTN_AUDIOTRACKS,
    BTN_AUX_ASSETS as BTN_AUX_ASSETS,
    BTN_BEATS_OOPS as BTN_BEATS_OOPS,
    BTN_BUSSES as BTN_BUSSES,
    BTN_CANCEL_CANCEL as BTN_CANCEL_CANCEL,
    BTN_CH1_ENCODER_ROTARYMODE as BTN_CH1_ENCODER_ROTARYMODE,
    BTN_CH1_MUTE_BLACK as BTN_CH1_MUTE_BLACK,
    BTN_CH1_REC_READY as BTN_CH1_REC_READY,
    BTN_CH1_SELECT_SELECT as BTN_CH1_SELECT_SELECT,
    BTN_CH1_SOLO_FLASH as BTN_CH1_SOLO_FLASH,
    BTN_CH2_ENCODER_ROTARYMODE as BTN_CH2_ENCODER_ROTARYMODE,
    BTN_CH2_MUTE_BLACK as BTN_CH2_MUTE_BLACK,
    BTN_CH2_REC_READY as BTN_CH2_REC_READY,
    BTN_CH2_SELECT_SELECT as BTN_CH2_SELECT_SELECT,
    BTN_CH2_SOLO_FLASH as BTN_CH2_SOLO_FLASH,
    BTN_CH3_ENCODER_ROTARYMODE as BTN_CH3_ENCODER_ROTARYMODE,
    BTN_CH3_MUTE_BLACK as BTN_CH3_MUTE_BLACK,
    BTN_CH3_REC_READY as BTN_CH3_REC_READY,
    BTN_CH3_SELECT_SELECT as BTN_CH3_SELECT_SELECT,
    BTN_CH3_SOLO_FLASH as BTN_CH3_SOLO_FLASH,
    BTN_CH4_ENCODER_ROTARYMODE as BTN_CH4_ENCODER_ROTARYMODE,
    BTN_CH4_MUTE_BLACK as BTN_CH4_MUTE_BLACK,
    BTN_CH4_REC_READY as BTN_CH4_REC_READY,
    BTN_CH4_SELECT_SELECT as BTN_CH4_SELECT_SELECT,
    BTN_CH4_SOLO_FLASH as BTN_CH4_SOLO_FLASH,
    BTN_CH5_ENCODER_ROTARYMODE as BTN_CH5_ENCODER_ROTARYMODE,
    BTN_CH5_MUTE_BLACK as BTN_CH5_MUTE_BLACK,
    BTN_CH5_REC_READY as BTN_CH5_REC_READY,
    BTN_CH5_SELECT_SELECT as BTN_CH5_SELECT_SELECT,
    BTN_CH5_SOLO_FLASH as BTN_CH5_SOLO_FLASH,
    BTN_CH6_ENCODER_ROTARYMODE as BTN_CH6_ENCODER_ROTARYMODE,
    BTN_CH6_MUTE_BLACK as BTN_CH6_MUTE_BLACK,
    BTN_CH6_REC_READY as BTN_CH6_REC_READY,
    BTN_CH6_SELECT_SELECT as BTN_CH6_SELECT_SELECT,
    BTN_CH6_SOLO_FLASH as BTN_CH6_SOLO_FLASH,
    BTN_CH7_ENCODER_ROTARYMODE as BTN_CH7_ENCODER_ROTARYMODE,
    BTN_CH7_MUTE_BLACK as BTN_CH7_MUTE_BLACK,
    BTN_CH7_REC_READY as BTN_CH7_REC_READY,
    BTN_CH7_SELECT_SELECT as BTN_CH7_SELECT_SELECT,
    BTN_CH7_SOLO_FLASH as BTN_CH7_SOLO_FLASH,
    BTN_CH8_ENCODER_ROTARYMODE as BTN_CH8_ENCODER_ROTARYMODE,
    BTN_CH8_MUTE_BLACK as BTN_CH8_MUTE_BLACK,
    BTN_CH8_REC_READY as BTN_CH8_REC_READY,
    BTN_CH8_SELECT_SELECT as BTN_CH8_SELECT_SELECT,
    BTN_CH8_SOLO_FLASH as BTN_CH8_SOLO_FLASH,
    BTN_CHNEXT_UNIVERSENEXT as BTN_CHNEXT_UNIVERSENEXT,
    BTN_CHPREV_UNIVERSEPREV as BTN_CHPREV_UNIVERSEPREV,
    BTN_CLICK_IMAGE as BTN_CLICK_IMAGE,
    BTN_CONTROL as BTN_CONTROL,
    BTN_CROSSENTER as BTN_CROSSENTER,
    BTN_CYCLE_SHUTTER as BTN_CYCLE_SHUTTER,
    BTN_DOWN_DOWN as BTN_DOWN_DOWN,
    BTN_DROP_COLOR as BTN_DROP_COLOR,
    BTN_ENTER_ENTER as BTN_ENTER_ENTER,
    BTN_EQ_SHOWUI as BTN_EQ_SHOWUI,
    BTN_F1_F1 as BTN_F1_F1,
    BTN_F2_F2 as BTN_F2_F2,
    BTN_F3_F3 as BTN_F3_F3,
    BTN_F4_F4 as BTN_F4_F4,
    BTN_F5_F5 as BTN_F5_F5,
    BTN_F6_F6 as BTN_F6_F6,
    BTN_F7_F7 as BTN_F7_F7,
    BTN_F8_F8 as BTN_F8_F8,
    BTN_FADERBANKNEXT_FADERBANKNEXT as BTN_FADERBANKNEXT_FADERBANKNEXT,
    BTN_FADERBANKPREV_FADERBANKPREV as BTN_FADERBANKPREV_FADERBANKPREV,
    BTN_FF_NEXTCUE as BTN_FF_NEXTCUE,
    BTN_FLIP_MAINDARK as BTN_FLIP_MAINDARK,
    BTN_GLOBALVIEW_COMMITRDY as BTN_GLOBALVIEW_COMMITRDY,
    BTN_GROUP as BTN_GROUP,
    BTN_INPUTS_EVENTS as BTN_INPUTS_EVENTS,
    BTN_INST_DEBUG as BTN_INST_DEBUG,
    BTN_LATCH as BTN_LATCH,
    BTN_LEFT_LEFT as BTN_LEFT_LEFT,
    BTN_MARKER_GOBO as BTN_MARKER_GOBO,
    BTN_MIDITRACKS_FIND as BTN_MIDITRACKS_FIND,
    BTN_NAMEVALUE_COMMITSHOW as BTN_NAMEVALUE_COMMITSHOW,
    BTN_NUDGE_STROBO as BTN_NUDGE_STROBO,
    BTN_OPTION as BTN_OPTION,
    BTN_OUTPUTS as BTN_OUTPUTS,
    BTN_PAN_EDITSHOW as BTN_PAN_EDITSHOW,
    BTN_PLAY_RUNCUE as BTN_PLAY_RUNCUE,
    BTN_PLUGIN_PATCH as BTN_PLUGIN_PATCH,
    BTN_READOFF_GOTO as BTN_READOFF_GOTO,
    BTN_REC_RECFRAME as BTN_REC_RECFRAME,
    BTN_REPLACE_TEMPERATURE as BTN_REPLACE_TEMPERATURE,
    BTN_REV_LASTCUE as BTN_REV_LASTCUE,
    BTN_RIGHT_RIGHT as BTN_RIGHT_RIGHT,
    BTN_SAVE_SAVE as BTN_SAVE_SAVE,
    BTN_SCRUB_JOGWHEELMODESWITCH as BTN_SCRUB_JOGWHEELMODESWITCH,
    BTN_SEND_VISUALIZER as BTN_SEND_VISUALIZER,
    BTN_SHIFT as BTN_SHIFT,
    BTN_SOLO_SPEED as BTN_SOLO_SPEED,
    BTN_STOP_STOPCUE as BTN_STOP_STOPCUE,
    BTN_TOUCH as BTN_TOUCH,
    BTN_TRACK_CONSOLE as BTN_TRACK_CONSOLE,
    BTN_TRIM as BTN_TRIM,
    BTN_UNDO_UNDO as BTN_UNDO_UNDO,
    BTN_UP_UP as BTN_UP_UP,
    BTN_USER as BTN_USER,
    BTN_WRITE_MOVEWINDOW as BTN_WRITE_MOVEWINDOW,
    ButtonCode as ButtonCode,
    ButtonState as ButtonState,
    FADERTOUCH_CH1 as FADERTOUCH_CH1,
    FADERTOUCH_CH2 as FADERTOUCH_CH2,
    FADERTOUCH_CH3 as FADERTOUCH_CH3,
    FADERTOUCH_CH4 as FADERTOUCH_CH4,
    FADERTOUCH_CH5 as FADERTOUCH_CH5,
    FADERTOUCH_CH6 as FADERTOUCH_CH6,
    FADERTOUCH_CH7 as FADERTOUCH_CH7,
    FADERTOUCH_CH8 as FADERTOUCH_CH8,
    FADERTOUCH_MAIN as FADERTOUCH_MAIN,
    add_fader_bank_set as add_fader_bank_set,
    black as black,
    blue as blue,
    button_state_change as button_state_change,
    cyan as cyan,
    desk_update as desk_update,
    fader_column as fader_column,
    fader_position as fader_position,
    green as green,
    lcd_color as lcd_color,
    magenta as magenta,
    red as red,
    remove_fader_bank_set as remove_fader_bank_set,
    rotary_encoder_change as rotary_encoder_change,
    white as white,
    yellow as yellow,
)
from DirectMode_pb2 import (
    dmx_output as dmx_output,
    request_dmx_data as request_dmx_data,
)
from FilterMode_pb2 import (
    SFAS_ERROR_SHOW_RUNNING as SFAS_ERROR_SHOW_RUNNING,
    SFAS_INVALID as SFAS_INVALID,
    SFAS_NO_SHOW_ERROR as SFAS_NO_SHOW_ERROR,
    SFAS_SHOW_ACTIVE as SFAS_SHOW_ACTIVE,
    SFAS_SHOW_LOADING as SFAS_SHOW_LOADING,
    SFAS_SHOW_UPDATING as SFAS_SHOW_UPDATING,
    ShowFileApplyState as ShowFileApplyState,
    enter_scene as enter_scene,
    load_show_file as load_show_file,
    update_parameter as update_parameter,
)
from UniverseControl_pb2 import (
    Universe as Universe,
    delete_universe as delete_universe,
    request_universe_list as request_universe_list,
    universes_list as universes_list,
)

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _RunMode:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _RunModeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_RunMode.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    RM_FILTER: _RunMode.ValueType  # 0
    """Goto filter mode if transmitted"""
    RM_DIRECT: _RunMode.ValueType  # 1
    """Goto direct mode if transmitted"""
    RM_STOP: _RunMode.ValueType  # 2
    """Stop the real time server if transmitted"""

class RunMode(_RunMode, metaclass=_RunModeEnumTypeWrapper):
    """
    This file specifies messages and types used for general control.
    It also imports the definitions from direct and filter mode.
    """

RM_FILTER: RunMode.ValueType  # 0
"""Goto filter mode if transmitted"""
RM_DIRECT: RunMode.ValueType  # 1
"""Goto direct mode if transmitted"""
RM_STOP: RunMode.ValueType  # 2
"""Stop the real time server if transmitted"""
Global___RunMode: typing_extensions.TypeAlias = RunMode

class _LogLevel:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _LogLevelEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_LogLevel.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    LL_DEBUG: _LogLevel.ValueType  # 0
    LL_INFO: _LogLevel.ValueType  # 1
    LL_WARNING: _LogLevel.ValueType  # 2
    LL_ERROR: _LogLevel.ValueType  # 3

class LogLevel(_LogLevel, metaclass=_LogLevelEnumTypeWrapper): ...

LL_DEBUG: LogLevel.ValueType  # 0
LL_INFO: LogLevel.ValueType  # 1
LL_WARNING: LogLevel.ValueType  # 2
LL_ERROR: LogLevel.ValueType  # 3
Global___LogLevel: typing_extensions.TypeAlias = LogLevel

class _ReadymodeUpdateCause:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ReadymodeUpdateCauseEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ReadymodeUpdateCause.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    RUC_ENTERED: _ReadymodeUpdateCause.ValueType  # 0
    RUC_ABORTED: _ReadymodeUpdateCause.ValueType  # 1
    RUC_COMMITED: _ReadymodeUpdateCause.ValueType  # 2

class ReadymodeUpdateCause(_ReadymodeUpdateCause, metaclass=_ReadymodeUpdateCauseEnumTypeWrapper): ...

RUC_ENTERED: ReadymodeUpdateCause.ValueType  # 0
RUC_ABORTED: ReadymodeUpdateCause.ValueType  # 1
RUC_COMMITED: ReadymodeUpdateCause.ValueType  # 2
Global___ReadymodeUpdateCause: typing_extensions.TypeAlias = ReadymodeUpdateCause

@typing.final
class update_state(google.protobuf.message.Message):
    """Tell Fish to enter a new run mode"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NEW_STATE_FIELD_NUMBER: builtins.int
    new_state: Global___RunMode.ValueType
    def __init__(
        self,
        *,
        new_state: Global___RunMode.ValueType = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["new_state", b"new_state"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___update_state: typing_extensions.TypeAlias = update_state

@typing.final
class current_state_update(google.protobuf.message.Message):
    """Will be pushed from Fish to UI after every cycle"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CURRENT_STATE_FIELD_NUMBER: builtins.int
    SHOWFILE_APPLY_STATE_FIELD_NUMBER: builtins.int
    CURRENT_SCENE_FIELD_NUMBER: builtins.int
    LAST_CYCLE_TIME_FIELD_NUMBER: builtins.int
    LAST_ERROR_FIELD_NUMBER: builtins.int
    current_state: Global___RunMode.ValueType
    showfile_apply_state: FilterMode_pb2.ShowFileApplyState.ValueType
    current_scene: builtins.int
    """Will be -1 if not applicable, -2 if filter mode requested but no show loaded"""
    last_cycle_time: builtins.int
    """Cycle time in ms"""
    last_error: builtins.str
    """The last error that occured"""
    def __init__(
        self,
        *,
        current_state: Global___RunMode.ValueType = ...,
        showfile_apply_state: FilterMode_pb2.ShowFileApplyState.ValueType = ...,
        current_scene: builtins.int = ...,
        last_cycle_time: builtins.int = ...,
        last_error: builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["current_scene", b"current_scene", "current_state", b"current_state", "last_cycle_time", b"last_cycle_time", "last_error", b"last_error", "showfile_apply_state", b"showfile_apply_state"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___current_state_update: typing_extensions.TypeAlias = current_state_update

@typing.final
class long_log_update(google.protobuf.message.Message):
    """This message will post log content to the GUI for every issue that is too long to be displayed within the status bar"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LEVEL_FIELD_NUMBER: builtins.int
    TIME_STAMP_FIELD_NUMBER: builtins.int
    WHAT_FIELD_NUMBER: builtins.int
    level: Global___LogLevel.ValueType
    time_stamp: builtins.int
    """Unix time stamp of event"""
    what: builtins.str
    """Content of the log entry"""
    def __init__(
        self,
        *,
        level: Global___LogLevel.ValueType = ...,
        time_stamp: builtins.int = ...,
        what: builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["level", b"level", "time_stamp", b"time_stamp", "what", b"what"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___long_log_update: typing_extensions.TypeAlias = long_log_update

@typing.final
class state_list(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class kvs(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        K_FIELD_NUMBER: builtins.int
        V_FIELD_NUMBER: builtins.int
        SCENE_ID_FIELD_NUMBER: builtins.int
        k: builtins.str
        v: builtins.str
        scene_id: builtins.int
        def __init__(
            self,
            *,
            k: builtins.str = ...,
            v: builtins.str = ...,
            scene_id: builtins.int = ...,
        ) -> None: ...
        _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["k", b"k", "scene_id", b"scene_id", "v", b"v"]
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @typing.final
    class UnspecificStatesEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["key", b"key", "value", b"value"]
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    UNSPECIFIC_STATES_FIELD_NUMBER: builtins.int
    SPECIFIC_STATES_FIELD_NUMBER: builtins.int
    @property
    def unspecific_states(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]: ...
    @property
    def specific_states(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___state_list.kvs]: ...
    def __init__(
        self,
        *,
        unspecific_states: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
        specific_states: collections.abc.Iterable[Global___state_list.kvs] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["specific_states", b"specific_states", "unspecific_states", b"unspecific_states"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___state_list: typing_extensions.TypeAlias = state_list

@typing.final
class readymode_update(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CAUSE_FIELD_NUMBER: builtins.int
    cause: Global___ReadymodeUpdateCause.ValueType
    def __init__(
        self,
        *,
        cause: Global___ReadymodeUpdateCause.ValueType = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["cause", b"cause"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___readymode_update: typing_extensions.TypeAlias = readymode_update
