"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import FilterMode_pb2
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions
from Console_pb2 import (
    BS_ACTIVE as BS_ACTIVE,
    BS_BUTTON_PRESSED as BS_BUTTON_PRESSED,
    BS_BUTTON_RELEASED as BS_BUTTON_RELEASED,
    BS_SET_LED_BLINKING as BS_SET_LED_BLINKING,
    BS_SET_LED_NOT_ACTIVE as BS_SET_LED_NOT_ACTIVE,
    ButtonState as ButtonState,
    add_fader_bank_set as add_fader_bank_set,
    button_state_change as button_state_change,
    fader_column as fader_column,
    fader_position as fader_position,
    remove_fader_bank_set as remove_fader_bank_set,
    rotary_encoder_change as rotary_encoder_change,
)
from DirectMode_pb2 import (
    dmx_output as dmx_output,
    request_dmx_data as request_dmx_data,
)
from FilterMode_pb2 import (
    SFAS_ERROR_SHOW_RUNNING as SFAS_ERROR_SHOW_RUNNING,
    SFAS_INVALID as SFAS_INVALID,
    SFAS_NO_SHOW_ERROR as SFAS_NO_SHOW_ERROR,
    SFAS_SHOW_ACTIVE as SFAS_SHOW_ACTIVE,
    SFAS_SHOW_LOADING as SFAS_SHOW_LOADING,
    SFAS_SHOW_UPDATING as SFAS_SHOW_UPDATING,
    ShowFileApplyState as ShowFileApplyState,
    enter_scene as enter_scene,
    load_show_file as load_show_file,
    update_parameter as update_parameter,
)
from UniverseControl_pb2 import (
    Universe as Universe,
    delete_universe as delete_universe,
    request_universe_list as request_universe_list,
    universes_list as universes_list,
)

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _RunMode:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _RunModeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_RunMode.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    RM_FILTER: _RunMode.ValueType  # 0
    """Goto filter mode if transmitted"""
    RM_DIRECT: _RunMode.ValueType  # 1
    """Goto direct mode if transmitted"""
    RM_STOP: _RunMode.ValueType  # 2
    """Stop the real time server if transmitted"""

class RunMode(_RunMode, metaclass=_RunModeEnumTypeWrapper):
    """
    This file specifies messages and types used for general control.
    It also imports the definitions from direct and filter mode.
    """

RM_FILTER: RunMode.ValueType  # 0
"""Goto filter mode if transmitted"""
RM_DIRECT: RunMode.ValueType  # 1
"""Goto direct mode if transmitted"""
RM_STOP: RunMode.ValueType  # 2
"""Stop the real time server if transmitted"""
global___RunMode = RunMode

class _LogLevel:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _LogLevelEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_LogLevel.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    LL_DEBUG: _LogLevel.ValueType  # 0
    LL_INFO: _LogLevel.ValueType  # 1
    LL_WARNING: _LogLevel.ValueType  # 2
    LL_ERROR: _LogLevel.ValueType  # 3

class LogLevel(_LogLevel, metaclass=_LogLevelEnumTypeWrapper): ...

LL_DEBUG: LogLevel.ValueType  # 0
LL_INFO: LogLevel.ValueType  # 1
LL_WARNING: LogLevel.ValueType  # 2
LL_ERROR: LogLevel.ValueType  # 3
global___LogLevel = LogLevel

@typing_extensions.final
class update_state(google.protobuf.message.Message):
    """Tell Fish to enter a new run mode"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NEW_STATE_FIELD_NUMBER: builtins.int
    new_state: global___RunMode.ValueType
    def __init__(
        self,
        *,
        new_state: global___RunMode.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["new_state", b"new_state"]) -> None: ...

global___update_state = update_state

@typing_extensions.final
class current_state_update(google.protobuf.message.Message):
    """Will be pushed from Fish to UI after every cycle"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CURRENT_STATE_FIELD_NUMBER: builtins.int
    SHOWFILE_APPLY_STATE_FIELD_NUMBER: builtins.int
    CURRENT_SCENE_FIELD_NUMBER: builtins.int
    LAST_CYCLE_TIME_FIELD_NUMBER: builtins.int
    LAST_ERROR_FIELD_NUMBER: builtins.int
    current_state: global___RunMode.ValueType
    showfile_apply_state: FilterMode_pb2.ShowFileApplyState.ValueType
    current_scene: builtins.int
    """Will be -1 if not applicable, -2 if filter mode requested but no show loaded"""
    last_cycle_time: builtins.int
    """Cycle time in ms"""
    last_error: builtins.str
    """The last error that occured"""
    def __init__(
        self,
        *,
        current_state: global___RunMode.ValueType = ...,
        showfile_apply_state: FilterMode_pb2.ShowFileApplyState.ValueType = ...,
        current_scene: builtins.int = ...,
        last_cycle_time: builtins.int = ...,
        last_error: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["current_scene", b"current_scene", "current_state", b"current_state", "last_cycle_time", b"last_cycle_time", "last_error", b"last_error", "showfile_apply_state", b"showfile_apply_state"]) -> None: ...

global___current_state_update = current_state_update

@typing_extensions.final
class long_log_update(google.protobuf.message.Message):
    """This message will post log content to the GUI for every issue that is too long to be displayed within the status bar"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LEVEL_FIELD_NUMBER: builtins.int
    TIME_STAMP_FIELD_NUMBER: builtins.int
    WHAT_FIELD_NUMBER: builtins.int
    level: global___LogLevel.ValueType
    time_stamp: builtins.int
    """Unix time stamp of event"""
    what: builtins.str
    """Content of the log entry"""
    def __init__(
        self,
        *,
        level: global___LogLevel.ValueType = ...,
        time_stamp: builtins.int = ...,
        what: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["level", b"level", "time_stamp", b"time_stamp", "what", b"what"]) -> None: ...

global___long_log_update = long_log_update
