"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Universe(google.protobuf.message.Message):
    """
    This file specifies messages used for manual universe routing.

    This will update or configure a new universe (based on the id) if send to fish
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class ArtNet(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        IP_ADDRESS_FIELD_NUMBER: builtins.int
        PORT_FIELD_NUMBER: builtins.int
        UNIVERSE_ON_DEVICE_FIELD_NUMBER: builtins.int
        ip_address: builtins.str
        port: builtins.int
        universe_on_device: builtins.int
        def __init__(
            self,
            *,
            ip_address: builtins.str = ...,
            port: builtins.int = ...,
            universe_on_device: builtins.int = ...,
        ) -> None: ...
        _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["ip_address", b"ip_address", "port", b"port", "universe_on_device", b"universe_on_device"]
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @typing.final
    class USBConfig(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        PRODUCT_ID_FIELD_NUMBER: builtins.int
        VENDOR_ID_FIELD_NUMBER: builtins.int
        DEVICE_NAME_FIELD_NUMBER: builtins.int
        SERIAL_FIELD_NUMBER: builtins.int
        product_id: builtins.int
        vendor_id: builtins.int
        device_name: builtins.str
        serial: builtins.str
        def __init__(
            self,
            *,
            product_id: builtins.int = ...,
            vendor_id: builtins.int = ...,
            device_name: builtins.str = ...,
            serial: builtins.str = ...,
        ) -> None: ...
        _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["device_name", b"device_name", "product_id", b"product_id", "serial", b"serial", "vendor_id", b"vendor_id"]
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    ID_FIELD_NUMBER: builtins.int
    PHYSICAL_LOCATION_FIELD_NUMBER: builtins.int
    REMOTE_LOCATION_FIELD_NUMBER: builtins.int
    FTDI_DONGLE_FIELD_NUMBER: builtins.int
    id: builtins.int
    physical_location: builtins.int
    @property
    def remote_location(self) -> Global___Universe.ArtNet: ...
    @property
    def ftdi_dongle(self) -> Global___Universe.USBConfig: ...
    def __init__(
        self,
        *,
        id: builtins.int = ...,
        physical_location: builtins.int = ...,
        remote_location: Global___Universe.ArtNet | None = ...,
        ftdi_dongle: Global___Universe.USBConfig | None = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["Location", b"Location", "ftdi_dongle", b"ftdi_dongle", "physical_location", b"physical_location", "remote_location", b"remote_location"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["Location", b"Location", "ftdi_dongle", b"ftdi_dongle", "id", b"id", "physical_location", b"physical_location", "remote_location", b"remote_location"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_Location: typing_extensions.TypeAlias = typing.Literal["physical_location", "remote_location", "ftdi_dongle"]
    _WhichOneofArgType_Location: typing_extensions.TypeAlias = typing.Literal["Location", b"Location"]
    def WhichOneof(self, oneof_group: _WhichOneofArgType_Location) -> _WhichOneofReturnType_Location | None: ...

Global___Universe: typing_extensions.TypeAlias = Universe

@typing.final
class universes_list(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LIST_OF_UNIVERSES_FIELD_NUMBER: builtins.int
    @property
    def list_of_universes(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___Universe]: ...
    def __init__(
        self,
        *,
        list_of_universes: collections.abc.Iterable[Global___Universe] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["list_of_universes", b"list_of_universes"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___universes_list: typing_extensions.TypeAlias = universes_list

@typing.final
class request_universe_list(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    UNIVERSE_ID_FIELD_NUMBER: builtins.int
    universe_id: builtins.int
    """Request info about a specific configured"""
    def __init__(
        self,
        *,
        universe_id: builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["universe_id", b"universe_id"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___request_universe_list: typing_extensions.TypeAlias = request_universe_list

@typing.final
class delete_universe(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    id: builtins.int
    def __init__(
        self,
        *,
        id: builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["id", b"id"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___delete_universe: typing_extensions.TypeAlias = delete_universe
