name: Build Python

on:
  workflow_call:

jobs:
  build-project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: install lib
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libxcb-xinerama0 libxcb-keysyms1 libxcb-icccm4 libxcb-shape0 libxcb-render-util0 libxcb-cursor0 libxcb-xkb1 libxkbcommon-x11-0 libxcb-image0 nvidia-cuda-toolkit python3-libnvinfer-dev
          version: 1.0

      - name: Set up CUDA repository
        run: |
          sudo apt-get update
          sudo apt-get install -y gnupg2 curl
          curl -fsSL https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/7fa2af80.pub | sudo gpg --dearmor -o /usr/share/keyrings/nvidia-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/nvidia-archive-keyring.gpg] https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64 /" | sudo tee /etc/apt/sources.list.d/cuda.list
          sudo apt-get update
          sudo apt-get install -y cuda-10.2 libcudnn8 libnvinfer10 libnvinfer-plugin10 libnvonnxparser10

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
        with:
          cache: true
          python-version-file: pyproject.toml

      - name: Install dependencies
        run: pdm install --dev

      - name: Run update_version.py and capture output
        id: version_update
        run: |
          RELEASE_TAG=$(pdm run python update_version.py info)
          echo "RELEASE_TAG=$RELEASE_TAG" >> $GITHUB_ENV

      - name: Build Python Executable
        run: |
          pdm run pyinstaller Project-Editor.spec

      - name: Upload Executable as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Project-Editor
          path: |
            dist/Project-Editor

      #- name: Create GitHub Release
      #  uses: softprops/action-gh-release@v1
      #  with:
      #    tag_name: ${{ env.RELEASE_TAG }}
      #    files: dist/Project-Editor
      #    generate_release_notes: true
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}