name: CI Pipeline

on:
  push:
    branches: [ main ]


jobs:
  read-commit:
    runs-on: [self-hosted]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
        submodules: true

      - name: Build Documentation
        run: doxygen Doxyfile

      - name: Deploy class documentation
        run: cd docs-build/html && sudo /home/deploy/deploy.bash . docs/editor-class-doc
