name: Build Python

on:
  workflow_call:

jobs:
  build-project:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/mission-dmx/builder:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Python Executable
        run: |
          pyinstaller --onefile --name=Project-Editor src/main.py

      - name: Upload Executables as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Project-Editor
          path: |
            dist/Project-Editor
