name: Build Executable

#on:
#  push:
#    branches:
#      - main
#  pull_request:
#    branches:
#      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (inkl. Submodule)
        uses: actions/checkout@v4
        with:
          submodules: true
