name: Build Python

on:
  workflow_call:

jobs:
  build-project:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/mission-dmx/builder:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Python Executable
        run: |
          pyinstaller --onefile --name=Project-Editor src/main.py

      - name: Create tar.gz Archive
        run: |
          tar -czvf dist/project-editor.tar.gz -C dist project-editor

      - name: Upload tar.gz as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: project-editor
          path: dist/project-editor.tar.gz