name: Build Python

on:
  workflow_call:

jobs:
  build-project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: install lib
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libxcb-xinerama0 libxcb-keysyms1 libxcb-icccm4 libxcb-shape0 libxcb-render-util0 libxcb-cursor0 libxcb-xkb1 libxkbcommon-x11-0 libxcb-image0 libtinfo5 cuda-toolkit-12-2
          version: 1.0

      - name: Install libtinfo5 manually
        run: |
          wget http://archive.ubuntu.com/ubuntu/pool/main/n/ncurses/libtinfo5_6.2-0ubuntu2_amd64.deb
          sudo dpkg -i libtinfo5_6.2-0ubuntu2_amd64.deb

      - name: Add NVIDIA CUDA repository
        run: |
          sudo apt-get update
          sudo apt-get install -y gnupg software-properties-common
          
          wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-ubuntu2204.pin
          sudo mv cuda-ubuntu2204.pin /etc/apt/preferences.d/cuda-repository-pin-600
          
          sudo apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/3bf863cc.pub
          sudo add-apt-repository "deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/ /"
          sudo apt-get update
          sudo apt-get install cuda-toolkit-12-2

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
        with:
          cache: true
          python-version-file: pyproject.toml

      - name: Install dependencies
        run: pdm install --dev

      - name: Run update_version.py and capture output
        id: version_update
        run: |
          RELEASE_TAG=$(pdm run python update_version.py info)
          echo "RELEASE_TAG=$RELEASE_TAG" >> $GITHUB_ENV

      - name: Build Python Executable
        run: |
          pdm run pyinstaller Project-Editor.spec

      - name: Upload Executable as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Project-Editor
          path: |
            dist/Project-Editor

      #- name: Create GitHub Release
      #  uses: softprops/action-gh-release@v1
      #  with:
      #    tag_name: ${{ env.RELEASE_TAG }}
      #    files: dist/Project-Editor
      #    generate_release_notes: true
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}