name: CI Pipeline

on:
  push:
    branches: [ main ]


jobs:
  read-commit:
    runs-on: ubuntu-latest
    outputs:
      commit_msg: ${{ steps.commit.outputs.commit_msg }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: get Commit-Message
        id: commit
        run: |
          msg=$(git log -1 --pretty=%B)
          echo "Commit message: $msg"
          echo "commit_msg=$msg" >> $GITHUB_OUTPUT

  generateVersionsPR:
    needs: read-commit
    if: ${{!contains(needs.read-commit.outputs.commit_msg, '[REBUILD]')}}
    uses: ./.github/workflows/update-version-pr.yml

  buildAndRelease:
    needs: read-commit
    if: ${{contains(needs.read-commit.outputs.commit_msg, '[REBUILD]')}}
    uses: ./.github/workflows/build-project.yml

