name: CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  generateVersionsPR:
    if: ${{!(github.event.pull_request.merged == true &&
      github.event.pull_request.head.ref == 'version-update')}}
    uses: ./.github/workflows/update-version-pr.yml

  buildAndRelease:
    if: ${{github.event.pull_request.merged == true &&
      github.event.pull_request.head.ref == 'version-update'}}
    uses: ./.github/workflows/build-project.yml

