name: CI Pipeline

on:
  pull_request:
    branches: [ main ]


jobs:
  show-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Zeige Branch-Namen des PRs
        run:
          echo ${{ github.event.pull_request.head.ref }}

  generateVersionsPR:
    if: ${{!(github.event.pull_request.merged == true &&
      github.event.pull_request.head.ref == 'version-update')||github.event_name == 'push'}}
    uses: ./.github/workflows/update-version-pr.yml

  buildAndRelease:
    if: ${{github.event.pull_request.merged == true &&
      github.event.pull_request.head.ref == 'version-update'}}
    uses: ./.github/workflows/build-project.yml

