name: CI Pipeline

on:
  push:
    branches: [ main ]


jobs:
  read-commit:
    runs-on: ubuntu-latest
    outputs:
      rebuild: ${{ steps.check.outputs.has_version_update }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Checke ob Commit-Message '[REBUILD]' enthält
        id: check
        run: |
          msg=$(git log -1 --pretty=%B)
          echo "Commit message:"
          echo $msg
          if echo "$msg" | grep -Fq "[REBUILD]"; then
            echo "has_version_update=true" >> $GITHUB_OUTPUT
            echo rebuild
          else
            echo "has_version_update=false" >> $GITHUB_OUTPUT
            echo version_update
          fi

  generateVersionsPR:
    needs: read-commit
    if: ${{needs.read-commit.outputs.rebuild == 'false'}}
    uses: ./.github/workflows/update-version-pr.yml

  buildAndRelease:
    needs: read-commit
    if: ${{needs.read-commit.outputs.rebuild == 'true'}}
    uses: ./.github/workflows/build-project.yml