name: CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  generateVersionsPR:
    if: ${{!github.ref == 'refs/tags/VERSION_UPDATE'}}
    uses: ./.github/workflows/update-version-pr.yml

  buildAndRelease:
    if: ${{github.ref == 'refs/tags/VERSION_UPDATE'}}
    uses: ./.github/workflows/build-project.yml

