name: Testing

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'pip'
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint
    - name: Check Import Order with isort
      uses: isort/isort-action@v1
    - name: Analysing the code with pylint
      run: |
        pylint --fail-under=8 $(git ls-files '*.py')
