name: Testing

on: [ pull_request ]

jobs:
  test_on_pr:
    if: github.base_ref != 'main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test with ruff
        uses: astral-sh/ruff-action@v3

  test_on_main_pr:
    if: github.base_ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test with ruff
        uses: astral-sh/ruff-action@v3
#        with:
#          args: 'check --extend-select ERA'
      - name: Get changed Python files
        id: changes
        run: |
          git fetch origin ${{ github.base_ref }}
          echo "files=$(git diff --name-only origin/${{ github.base_ref }} -- '*.py' | tr '\n' ' ')" >> "$GITHUB_OUTPUT"

      - name: Run Ruff on changed files (only D rules)
        run: |
          if [ -n "${{ steps.changes.outputs.files }}" ]; then
            ruff check --select D ${{ steps.changes.outputs.files }}
          else
            echo "No Python files changed."
          fi


