name: Update Version Bump

on:
  pull_request:
    types:
      - closed
    branches:
      - main

permissions:
  contents: write

jobs:
  update-version:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          fetch-depth: 0
          ref: main

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
        with:
          cache: false
          python-version-file: pyproject.toml

      - name: Configure git
        run: |
          git config user.name "MissionDMX Release Bot"
          git config user.email "4304726+mission-dmx-version-bot[bot]@users.noreply.github.com"

      - name: Install pdm bump
        run: pdm plugin add pdm-bump

      - name: Run pdm bump
        run: pdm bump auto

      - name: Push changes
        run: |
          git push origin main --follow-tags || echo "Nothing to push"